steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Downloading proxy bundle from GCS..."
        gsutil cp gs://proxy-storage-01/helloworld-1.zip .

  - name: 'gcr.io/cloud-builders/unzip'
    args: ['helloworld-1.zip']

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Deploying proxy to Apigee..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/test-env/apis?action=import&name=helloworld-1" \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -F "file=@helloworld-1.zip"
