steps:
  # Define the environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'variables'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export ORGANIZATION_ID="apigee-x-379708"
        export ENV_SRC="default-dev"
        export ENV_DEST="test-env"
        export KVM_NAME="SampleKVM"
        export ACCESS_TOKEN=$(gcloud auth print-access-token)

  # Check if the KVM exists in the source environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'check_kvm_exists'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        KVM_CHECK_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${ACCESS_TOKEN}" "https://apigee.googleapis.com/v1/organizations/${ORGANIZATION_ID}/environments/${ENV_SRC}/keyvaluemaps/${KVM_NAME}")
        if [ "$KVM_CHECK_RESPONSE" -ne 200 ]; then
          echo "KVM ${KVM_NAME} not found in ${ENV_SRC} environment. Aborting."
          exit 1
        fi

  # Export the KVM from the source environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'export_kvm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Exporting KVM from ${ENV_SRC} environment..."
        curl -s -H "Authorization: Bearer ${ACCESS_TOKEN}" "https://apigee.googleapis.com/v1/organizations/${ORGANIZATION_ID}/environments/${ENV_SRC}/keyvaluemaps/${KVM_NAME}" -o kvm_export.json
        if [ ! -s kvm_export.json ]; then
          echo "Error: KVM export failed. Aborting."
          exit 1
        fi

  # Import the KVM to the destination environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'import_kvm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Importing KVM to ${ENV_DEST} environment..."
        curl -s -X POST -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "Content-Type: application/json" "https://apigee.googleapis.com/v1/organizations/${ORGANIZATION_ID}/environments/${ENV_DEST}/keyvaluemaps" -d @kvm_export.json -o import_response.json
        if grep -q '"error"' import_response.json; then
          echo "Error: KVM import failed."
          cat import_response.json
          exit 1
        fi

timeout: 1200s
