steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: create_kvm_if_needed
    entrypoint: 'bash'
    args:
      - -c
      - |
        gcloud auth application-default print-access-token > /workspace/build_vars
        export build_token="$(< /workspace/build_vars)"
        curl -X POST -H "Authorization: Bearer $build_token" -H "Content-Type: application/json" -d '{"name": "SampleKVM"}' https://api.enterprise.apigee.com/v1/organizations/apigee-x-379708/environments/default-dev/keyvaluemaps
  - name: 'gcr.io/cloud-builders/curl'
    id: export_kvm
    entrypoint: 'bash'
    args:
      - -c
      - |
        curl -X GET -H "Authorization: Bearer $build_token" https://api.enterprise.apigee.com/v1/organizations/apigee-x-379708/environments/default-dev/keyvaluemaps/SampleKVM > /workspace/exported_kvm.json
  - name: 'gcr.io/cloud-builders/curl'
    id: import_kvm
    entrypoint: 'bash'
    args:
      - -c
      - |
        curl -X POST -H "Authorization: Bearer $build_token" -H "Content-Type: application/json" -d @/workspace/exported_kvm.json https://api.enterprise.apigee.com/v1/organizations/apigee-x-379708/environments/test-env/keyvaluemaps
