steps:
  # Step to generate access token
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export _TOKEN="$(gcloud auth application-default print-access-token)"
        echo "Token: $_TOKEN"

  # Step to import the KVM into the test-env environment
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X POST \
        -H "Authorization: Bearer $_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
          "name": "SampleKVM",
          "encrypted": false,
          "entry": [
            {
              "name": "key1",
              "value": "value1"
            },
            {
              "name": "key2",
              "value": "value2"
            }
          ]
        }' \
        "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/test-env/keyvaluemaps"
