steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: export_kvm
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Exporting KVM from default-dev environment..."
        source /workspace/build_vars
        curl -H "Authorization: Bearer $build_token" \
             -H "Content-Type: application/json" \
             "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/default-dev/keyvaluemaps/SampleKVM" \
             -o kvm_export.json
        echo "Exported KVM content:"
        cat kvm_export.json

  - name: 'gcr.io/cloud-builders/curl'
    id: import_kvm
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Importing KVM to test-env environment..."
        source /workspace/build_vars
        if grep -q "<!DOCTYPE html>" kvm_export.json; then
          echo "Error: Exported KVM content is not valid JSON. Aborting import."
          exit 1
        fi
        curl -X POST -H "Authorization: Bearer $build_token" \
             -H "Content-Type: application/json" \
             -d @kvm_export.json \
             "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/test-env/keyvaluemaps"
