steps:
  # Step 0: Generate Access Token
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        echo "build_token=$build_token" > /workspace/build_vars

  # Step 1: Export KVM from default-dev environment
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'GET'
      - 'https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/default-dev/keyvaluemaps/SampleKVM'
      - '-H'
      - 'Authorization: Bearer $(cat /workspace/build_vars | grep build_token | cut -d'=' -f2)'
    id: 'export-kvm'

  # Step 2: Import KVM to test-env environment
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'POST'
      - 'https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/test-env/keyvaluemaps'
      - '-H'
      - 'Authorization: Bearer $(cat /workspace/build_vars | grep build_token | cut -d'=' -f2)'
      - '-H'
      - 'Content-Type: application/json'
      - '--data-binary'
      - |
        {
          "name": "SampleKVM",
          "encrypted": false,
          "entry": [
            {
              "name": "key1",
              "value": "value1"
            },
            {
              "name": "key2",
              "value": "value2"
            }
            // Add more key-value pairs if needed
          ]
        }
