steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default \
          print-access-token)\"

        # write all "build_" variables to the persistent volume "/workspace"
        env | grep "^build_" > /workspace/build_vars
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Process resources (copy to target dir and replace env)"
    entrypoint: 'bash'
    args:
      - -c
      - |
        mvn -f deploy-apigee-config/pom.xml -ntp process-resources \
          -Dorg=$PROJECT_ID -Denv=$_APIGEE_TEST_ENV
  - name: 'ubuntu'
    id: "List files in target/config"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Listing contents of target/config directory:"
        ls -R deploy-apigee-config/target/config
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Push Apigee Environment configurations"
    entrypoint: 'bash'
    args:
      - -c
      - |
        # Read environment variables from disk
        echo current working directory
        echo pwd
        source /workspace/build_vars &&
        mvn -f deploy-apigee-config/pom.xml -ntp apigee-config:targetservers \
          apigee-config:keyvaluemaps -Pdev \
          -Dorg=$PROJECT_ID -Denv=$_APIGEE_TEST_ENV \
          -Dbearer=${build_token} -Doptions=create
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Push Apigee Org configurations"
    entrypoint: 'bash'
    args:
      - -c
      - |
        # Read environment variables from disk
        source /workspace/build_vars &&
        mvn -f deploy-apigee-config/pom.xml -ntp apigee-config:apiproducts \
          -Dapiproducts.path=deploy-apigee-config/config/apiProducts.json \
          apigee-config:developers \
          -Ddevelopers.path=deploy-apigee-config/config/developers.json \
          apigee-config:apps \
          -Dapps.path=deploy-apigee-config/config/developerApps.json -Pdev \
          -Dorg=$PROJECT_ID -Denv=$_APIGEE_TEST_ENV \
          -Dbearer=${build_token} -Doptions=create
