steps:
  - name: 'gcr.io/cloud-builders/mvn'
    id: "Process resources (copy to target dir and replace env)"
    entrypoint: 'bash'
    args:
      - -c
      - |
        mvn -f deploy-apigee-config/pom.xml -ntp process-resources -Dorg=$PROJECT_ID -Denv=$_APIGEE_TEST_ENV
        mkdir -p /workspace/target/config/env/default-dev
        mkdir -p /workspace/target/config/org
        cp -r config/env/default-dev/* /workspace/target/config/env/default-dev/
        cp -r config/org/* /workspace/target/config/org/
        echo "Contents of /workspace/target/config/env/default-dev:"
        ls -R /workspace/target/config/env/default-dev
        echo "Contents of /workspace/target/config/org:"
        ls -R /workspace/target/config/org

  - name: 'gcr.io/cloud-builders/mvn'
    id: "Push Apigee Environment configurations"
    entrypoint: 'bash'
    args:
      - -c
      - |
        mvn -f deploy-apigee-config/pom.xml -ntp apigee-config:targetservers apigee-config:keyvaluemaps -Pdev -Dorg=$PROJECT_ID -Denv=$_APIGEE_TEST_ENV
