steps:
  # Step 1: Read environment variables from build_vars file
  - name: 'gcr.io/cloud-builders/bash'
    id: read-vars
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -o allexport
        source /workspace/build_vars
        set +o allexport

  # Step 2: Export and deploy each proxy
  - name: 'gcr.io/cloud-builders/curl'
    id: export-deploy
    entrypoint: 'bash'
    env:
      - "build_token=${build_token}"
    args:
      - -c
      - |
        # Define the list of proxies
        proxies=("FirstTemplateProxy" "generateReport" "GetAttachmentLists")
        
        # Define your Apigee organization and environments
        org="apigee-x-379708"
        dev_env="default-dev"
        test_env="test-env"

        for proxy in "${proxies[@]}"; do
          echo "Processing proxy: $proxy"

          # Export the proxy
          export_url="https://apigee.googleapis.com/v1/organizations/$org/apis/$proxy/revisions/1?format=bundle"
          curl -X GET "$export_url" -H "Authorization: Bearer $build_token" -o "/workspace/$proxy.zip"
          
          # Check if the export was successful
          if [ $? -eq 0 ]; then
            echo "Proxy export successful: $proxy"
          else
            echo "Proxy export failed: $proxy"
            exit 1
          fi

          # Import and deploy to test environment
          import_url="https://apigee.googleapis.com/v1/organizations/$org/environments/$test_env/apis?action=import&name=$proxy"
          curl -X POST "$import_url" -H "Authorization: Bearer $build_token" -H "Content-Type: multipart/form-data" -F "file=@/workspace/$proxy.zip"
          
          # Extract revision number from the proxy bundle
          revision=$(unzip -p "/workspace/$proxy.zip" apiproxy/*.xml | grep -oP '(?<=<Version>)[^<]+')
          deploy_url="https://apigee.googleapis.com/v1/organizations/$org/environments/$test_env/apis/$proxy/revisions/$revision/deployments"
          curl -X POST "$deploy_url" -H "Authorization: Bearer $build_token"
        done

# Define substitutions (modify as needed)
substitutions:
  _env: 'default-dev'
  _env_test: 'test-env'
  _org: 'apigee-x-379708'

# Define timeout (optional)
timeout: '1200s'
