steps:
- name: 'ubuntu'
  id: 'Download Proxy Bundle'
  args: ['curl', '-o', '/workspace/proxies.zip', 'https://storage.googleapis.com/proxy-storage-01/proxies.zip']

- name: 'ubuntu'
  id: 'Verify Download'
  args: ['sha256sum', '/workspace/proxies.zip']

- name: 'ubuntu'
  id: 'Install dependencies'
  args:
    - '/bin/sh'
    - '-c'
    - |
      apt-get update
      apt-get install -y unzip jq curl

- name: 'ubuntu'
  id: 'Unzip Proxy Bundle'
  args: ['unzip', '-o', '/workspace/proxies.zip', '-d', '/workspace']

- name: 'ubuntu'
  id: 'Read and parse proxies.json'
  entrypoint: 'jq'
  args: ['.', '/workspace/proxies.json']
  waitFor: ['Install dependencies', 'Unzip Proxy Bundle']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: 'Deploy Proxies'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      for proxy in $(jq -r '.proxies | keys[]' /workspace/proxies.json); do
        PROXY_NAME=$(jq -r ".proxies[$proxy].name" /workspace/proxies.json)
        PROXY_DIR=$(jq -r ".proxies[$proxy].directory" /workspace/proxies.json)
        echo "Deploying ${PROXY_NAME} from ${PROXY_DIR}"
        if gcloud alpha apigee apis describe ${PROXY_NAME} --organization='apigee-x-379708'; then
          echo "API ${PROXY_NAME} already exists"
        else
          gcloud alpha apigee apis create ${PROXY_NAME} --organization='apigee-x-379708'
        fi
        gcloud alpha apigee apis deploy ${PROXY_NAME} --environment='test-env' --source=${PROXY_DIR}
      done
  waitFor: ['Read and parse proxies.json']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: 'Clean up'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      rm -rf /workspace/proxies.zip
      find /workspace -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} +
  waitFor: ['Deploy Proxies']

timeout: 1200s
