steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: List Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Listing proxies in default-dev environment..."
        curl -s -X GET "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/default-dev/apis" \
          -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
          | jq -r '.[]' > proxies.txt

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Download Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Downloading proxy bundles from default-dev environment..."
        while IFS= read -r proxy; do
          echo "Downloading proxy: $proxy"
          gsutil cp "gs://proxy-storage-01/$proxy.zip" "/workspace/$proxy.zip"
        done < proxies.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Proxies to Test Environment
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deploying proxies to test-env environment..."
        while IFS= read -r proxy; do
          echo "Deploying proxy: $proxy"
          curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/test-env/apis/$proxy/revisions/latest/deployments" \
            -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
            -H "Content-Type: application/json" \
            -d '{}'
        done < proxies.txt

images:
  - gcr.io/cloud-builders/gcloud
  - gcr.io/cloud-builders/gsutil

timeout: "3600s"
