steps:
  # Step 1: Install jq (optional, removed since we don't need it now)
  #- name: 'gcr.io/cloud-builders/curl'
  #  id: install-jq
  #  entrypoint: 'bash'
  #  args:
  #    - -c
  #    - |
  #      apt-get update && apt-get install -y jq

  # Step 2: Export and deploy each proxy
  - name: 'gcr.io/cloud-builders/gcloud'
    id: export-deploy
    entrypoint: 'bash'
    args:
      - -c
      - |
        # Define the list of proxies
        proxies=("FirstTemplateProxy" "generateReport" "GetAttachmentLists")

        for proxy in "${proxies[@]}"; do
          echo "Processing proxy: $proxy"

          # Export the proxy
          gcloud apigee apis export $proxy --environment=default-dev --zip-file=/workspace/$proxy.zip

          # Deploy to test environment
          gcloud apigee apis import --name=$proxy --file=/workspace/$proxy.zip
          gcloud apigee apis deploy --name=$proxy --environment=test-env
        done

# Define substitutions (modify as needed)
substitutions:
  _ENV: 'default-dev'
  _TARGET_ENV: 'test-env'

# Define timeout (optional)
timeout: '1200s'
