steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: bash
    args:
      - -c
      - |
        # Set necessary variables here
        export PROJECT_ID=$(gcloud config get-value project)
        export ORG_NAME="apigee-x-379708"
        export ENV_NAME="test-env"
        echo "PROJECT_ID: $PROJECT_ID"
        echo "ORG_NAME: $ORG_NAME"
        echo "ENV_NAME: $ENV_NAME"

  - name: 'gcr.io/cloud-builders/curl'
    id: List Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Listing proxies in $ENV_NAME environment..."
        PROXIES=$(curl -s -X GET "https://apigee.googleapis.com/v1/organizations/$ORG_NAME/environments/$ENV_NAME/apis" \
          -H "Authorization: Bearer $(gcloud auth print-access-token)")

        echo "Proxies fetched:"
        echo "$PROXIES"

        # Save proxies to a file for further processing
        echo "$PROXIES" > proxies.json

  - name: 'ubuntu'
    id: Install JQ and Process Proxies
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y jq

        echo "Processing proxy list..."
        
        # Read proxies.json file and process with jq
        cat proxies.json | jq '.'

        # Example: Extract the proxy names
        PROXY_NAMES=$(cat proxies.json | jq -r '.[]')
        echo "Proxy names extracted:"
        echo "$PROXY_NAMES"

        # Save the processed proxy names to a file
        echo "$PROXY_NAMES" > proxy_names.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Download Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Downloading proxy bundles..."
        while IFS= read -r proxy; do
          echo "Downloading proxy: $proxy"
          curl -s -X GET "https://apigee.googleapis.com/v1/organizations/$ORG_NAME/apis/$proxy/revisions/latest?format=bundle" \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            -o "${proxy}.zip"
        done < proxy_names.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Proxies to Test Environment
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deploying proxies to $ENV_NAME environment..."
        while IFS= read -r proxy; do
          echo "Deploying proxy: $proxy"
          curl -X POST "https://apigee.googleapis.com/v1/organizations/$ORG_NAME/environments/$ENV_NAME/apis/$proxy/revisions/latest/deployments" \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            -H "Content-Type: application/json" \
            -d '{}'
        done < proxy_names.txt

images:
  - gcr.io/cloud-builders/gcloud
  - gcr.io/cloud-builders/curl
  - ubuntu:latest

timeout: "3600s"
