steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default print-access-token)\"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: "List Proxies"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Listing proxies in default-dev environment..."
        curl -s -X GET "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/${_APIGEE_DEV_ENV}/apis" \
        -H "Authorization: Bearer ${build_token}" \
        -o /workspace/proxies.json

  - name: 'ubuntu'
    id: "Install JQ and Process Proxies"
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get update && apt-get install -y jq
        source /workspace/build_vars
        echo "Processing proxy list..."
        jq -r '.proxies[]' /workspace/proxies.json > /workspace/proxy_list.txt

  - name: 'ubuntu'
    id: "Download and Deploy Proxies"
    entrypoint: 'bash'
    args:
      - -c
      - |
        apt-get update && apt-get install -y curl unzip
        source /workspace/build_vars
        while read -r proxy; do
          echo "Processing $proxy..."
          gsutil cp gs://proxy-storage-01/${proxy}.zip /workspace/${proxy}.zip
          file /workspace/${proxy}.zip
          unzip -d /workspace/${proxy} /workspace/${proxy}.zip
          echo "Deploying $proxy to Apigee test environment..."
          curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/apis?action=import&name=${proxy}" \
          -H "Authorization: Bearer ${build_token}" \
          -F "file=@/workspace/${proxy}.zip"
          curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/${_APIGEE_UAT_ENV}/apis/${proxy}/revisions/1/deployments" \
          -H "Authorization: Bearer ${build_token}"
        done < /workspace/proxy_list.txt

substitutions:
  _APIGEE_DEV_ENV: "default-dev"
  _APIGEE_UAT_ENV: "test-env"
