steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: List Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Listing proxies in default-dev environment..."
        PROXIES=$(curl -s -X GET "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/default-dev/apis" \
          -H "Authorization: Bearer $(gcloud auth application-default print-access-token)")
        echo "Proxies fetched:"
        echo "$PROXIES"
        echo "$PROXIES" > proxies.json

  - name: 'ubuntu'
    id: Install JQ and Process Proxies
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update && apt-get install -y jq
        echo "Processing proxy list..."
        cat proxies.json | jq '.'
        PROXY_NAMES=$(cat proxies.json | jq -r '.[]')
        echo "Proxy names extracted:"
        echo "$PROXY_NAMES"
        echo "$PROXY_NAMES" > proxy_names.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Download Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Downloading proxy bundles from default-dev environment..."
        while IFS= read -r proxy; do
          echo "Downloading proxy: $proxy"
          curl -s -X GET "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/apis/$proxy/revisions/latest?format=bundle" \
            -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
            -o "${proxy}.zip"
        done < proxy_names.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Proxies to Test Environment
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deploying proxies to test-env environment..."
        while IFS= read -r proxy; do
          echo "Deploying proxy: $proxy"
          curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/test-env/apis/$proxy/revisions/latest/deployments" \
            -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
            -H "Content-Type: application/json" \
            -d '{}'
        done < proxy_names.txt

images:
  - gcr.io/cloud-builders/gcloud
  - ubuntu:latest

timeout: "3600s"
