steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/gcloud'
    id: "List Proxies"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Listing proxies in ${_APIGEE_DEV_ENV} environment..."
        gcloud config set project $PROJECT_ID
        gcloud apigee apis list --organization=apigee-x-379708 --format=json > /workspace/proxies.json

  - name: 'ubuntu'
    id: "Download and Deploy Proxies"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Downloading and deploying proxies..."
        apt-get update && apt-get install -y jq curl unzip
        source /workspace/build_vars
        for proxy in $(jq -r '.[].name' /workspace/proxies.json); do
          echo "Processing proxy: $proxy"
          revision=$(gcloud apigee apis describe $proxy --organization=apigee-x-379708 --format="value(latestRevision.id)")
          echo "Downloading proxy $proxy revision $revision"
          gcloud apigee apis export --organization=apigee-x-379708 --api=$proxy --revision=$revision --output=/workspace/$proxy.zip
          echo "Deploying proxy $proxy to ${_APIGEE_UAT_ENV} environment..."
          curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/apis?action=import&name=$proxy" \
          -H "Authorization: Bearer ${build_token}" \
          -F "file=@/workspace/$proxy.zip"
          curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/${_APIGEE_UAT_ENV}/apis/$proxy/revisions/$revision/deployments" \
          -H "Authorization: Bearer ${build_token}"
        done

substitutions:
  _APIGEE_DEV_ENV: "default-dev"
  _APIGEE_UAT_ENV: "test-env"
