steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: List Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Listing proxies in default-dev environment..."
        apt-get update && apt-get install -y jq
        response=$(curl -s -X GET "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/default-dev/apis" \
          -H "Authorization: Bearer $(gcloud auth application-default print-access-token)")
        proxies=$(echo "$response" | jq -r '.[].name')
        echo "$proxies" > proxies.txt

  - name: 'gcr.io/cloud-builders/gsutil'
    id: Download Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Downloading proxy bundles from default-dev environment..."
        while IFS= read -r proxy; do
          if [ ! -z "$proxy" ]; then
            echo "Downloading proxy: $proxy"
            gsutil cp "gs://proxy-storage-01/$proxy.zip" "/workspace/$proxy.zip"
          fi
        done < proxies.txt

  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Proxies
    entrypoint: bash
    args:
      - -c
      - |
        echo "Deploying proxies to test-env..."
        while IFS= read -r proxy; do
          if [ ! -z "$proxy" ]; then
            echo "Deploying proxy: $proxy"
            gcloud apigee proxies deploy --organization=apigee-x-379708 --environment=test-env --api="$proxy" --basepath="/" --bundle="/workspace/$proxy.zip"
          fi
        done < proxies.txt

images:
  - gcr.io/cloud-builders/gcloud
  - gcr.io/cloud-builders/gsutil

timeout: "3600s"
