steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default print-access-token)\"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/gsutil'
    id: "Download Proxies from default-dev"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Downloading all proxies from default-dev environment..."
        gcloud apigee environments list --format="value(name)" --filter="name=default-dev" | xargs -I {} gcloud apigee apis list --environment={} --format="value(name)" | xargs -I {} gcloud apigee apis get --name={} --format=json > /workspace/proxies.json

  - name: 'gcr.io/cloud-builders/gsutil'
    id: "Upload Proxies to proxy-storage-01"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Uploading proxies to proxy-storage-01 bucket..."
        gsutil cp /workspace/proxies.json gs://proxy-storage-01/

  - name: 'ubuntu'
    id: "Verify Proxies JSON"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Verifying downloaded proxies JSON..."
        cat /workspace/proxies.json

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Proxies to test-env"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying proxies to Apigee test environment..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/apis?action=import" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Content-Type: application/json" \
        -d @/workspace/proxies.json

substitutions:
  _APIGEE_DEV_ENV: "default-dev"
  _APIGEE_UAT_ENV: "test-env"
