steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: download-proxies
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Downloading proxies from default-dev environment..."
        gcloud apigee apis list --environment=default-dev --format=json > /workspace/proxies.json

  - name: 'gcr.io/cloud-builders/gsutil'
    id: upload-proxies
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Uploading proxies to proxy-storage-01 bucket..."
        gsutil cp /workspace/proxies.json gs://proxy-storage-01/proxies.json
